products=[
    {
        name:"Fridge",
        quantity:"10",
        price:200
    },
    {
        name:"AC",
        quantity:"5",
        price:500
    },
    {
        name:"oven",
        quantity:"7",
        price:400
    },
    {
        name:"Stationary",
        quantity:"6",
        price:600
    }
];
add1=[];
module.exports.products=products;
module.exports.add1=add1;